project:
  type: website
  output-dir: ../docs
  resources:
  - data/**
website:
  title: GPX Analysis
  navbar:
    left:
    - href: index.qmd
      text: Routes
    - text: Route Notes
      menu:
      - href: routes/arlington.qmd
        text: Arlington Gravel Loop
      - href: routes/grizzly.qmd
        text: Grizzly Peak Loop
      - href: routes/tunnel.qmd
        text: Tunnel to Pinehurst Loop
      - href: routes/spruce_to_euclid.qmd
        text: Spruce up, Euclid Down
      - href: routes/wildwood.qmd
        text: Wildwood to BBR Loop
      - href: routes/three_bears.qmd
        text: Three Bears with Gravel Loop
      - href: routes/redwood.qmd
        text: Redwood -- San Leandro to Macarthur BART
format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
execute:
  echo: false
  warning: false
  message: false
  freeze: auto
