project:
  type: website
  output-dir: ../docs
  resources:
  - data/**
website:
  title: GPX Analysis
  navbar:
    left:
    - href: index.qmd
      text: Routes
    - text: Route Notes
      menu:
      - href: routes/arlington.qmd
        text: Arlington Gravel Loop
      - href: routes/grizzly.qmd
        text: Grizzly Peak
      - href: routes/tunnel.qmd
        text: Tunnel to Pinehurst
format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
execute:
  echo: false
  warning: false
  message: false
  freeze: auto
